### ISSUE TITLE
Any inspiration source for setting SGD @ lr=0.1 ?

### ISSUE THREAD

**Issue by jaymefosa** [HyelinNAM/ContrastiveDenoisingScore#1]
https://github.com/HyelinNAM/ContrastiveDenoisingScore/blob/310b15d96f7583623d1e8f3e511fcb37cbf6c969/pipeline_cds.py#L141C45-L141C45

It kind of reminds me of the orthogonal delta rotation network that sets a super high learning rate. Was there any source/reason for this choice?

**Comment by HyelinNAM** [comment]
Hello @jaymefosa 

Most of the configs include learning rate are inherited from official implementation of DDS. (https://github.com/google/prompt-to-prompt/blob/main/DDS_zeroshot.ipynb)
