### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by balabala932131** [HyelinNAM/ContrastiveDenoisingScore#10]
hi, can u share or release your dataset. we want to compare some examples.

thanks!

**Comment by HyelinNAM** [comment]
Hi, I sent you through your email. (zhm21@mails.tsinghua.edu.cn)
Please check it if you have a chance.

Thank you for the interest!

**Comment by chaeoni** [comment]
Hi there! Could I possibly have access to the dataset as well? I’m hoping to use it for the same purpose as the previous request. Thanks!!
