### ISSUE TITLE
Dino-vit structure distance

### ISSUE THREAD

**Issue by codonna9** [HyelinNAM/ContrastiveDenoisingScore#12]
Hi, thank you very much for releasing the source code of this powerful method. I'm a bit confused about "Dino-vit structure distance". Do you mean, you get the key vectors from the attention module, calculate the cosine distance among them, then choose the maximum distance? If possible, can you show me the code to calculate that distance?

**Comment by HyelinNAM** [comment]
Hi Thank you for your interest!
Please let me know your preferred email here or just email me ([hyelin.nam@kaist.ac.kr](mailto:hyelin.nam@kaist.ac.kr)).
I'll send you the evaluation code.

**Comment by codonna9** [comment]
Thanks a lot for your reply. I just sent you an email

**Comment by AnnaFace** [comment]
Hi, thank you very much for releasing the source code of this powerful method. I'm a bit confused about the "Dino-vit structure distance." Do you mean that you get the key vectors from the attention module, calculate the cosine distance among them, and then choose the maximum distance? If possible, could you show me the code to calculate this distance and your evaluation code?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HyelinNAM/ContrastiveDenoisingScore"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月19日(星期二) 中午11:51
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [HyelinNAM/ContrastiveDenoisingScore] Dino-vit structure distance (Issue #12)





 
Hi Thank you for your interest!
 Please let me know your preferred email here or just email me ***@***.***).
