### ISSUE TITLE
A little confused about hidden state saving

### ISSUE THREAD

**Issue by jaymefosa** [HyelinNAM/ContrastiveDenoisingScore#2]
If the size of the batch is 4 from this set:
```
                # get score for dds & reference attention maps
                eps_pred = dds_loss.get_epsilon_prediction(
                    torch.cat((z_t_src, z_t_trg)),
                    torch.cat((timestep, timestep)),
                    torch.cat((prompt_embeds, trg_prompt_embeds))
                )
```
Then here wouldn't 2:3 be grabbing the trgt prompt embeds? 

```
        # save text-conditioned attention map only
        # get attention map of ref
        if hidden_states.shape[0] == 4: 
            attn.hs = hidden_states[2:3]
        # get attention map of trg
        else:
            attn.hs = hidden_states[1:2]
```

The comment indicates it should be ref (src) so I switched it to 1:2 and the overall edit behavior was similar, a little bit more destructive to the scene colors and shapes of the catpig

Could you help me understand this part?

**Comment by HyelinNAM** [comment]
Please refer below 'reshape' code. 

    def get_epsilon_prediction(self, z_t, timestep, embedd, guidance_scale=7.5, cross_attention_kwargs=None):


        latent_input = torch.cat([z_t] * 2)
        timestep = torch.cat([timestep] * 2)
        embedd = embedd.permute(1, 0, 2, 3).reshape(-1, *embedd.shape[2:])
