### ISSUE TITLE
A suggestion

### ISSUE THREAD

**Issue by CostaliyA** [HyelinNAM/ContrastiveDenoisingScore#4]
Thank you for releasing your fantastic work code, and congratulations on your acceptance at CVPR2024. I have a small suggestion in your Setup section. The current dependency files may conflict and have a lot of redundancy. You only need a few lines of code to setup the proper environment:
`conda install pytorch==2.1.1 torchvision==0.16.1 torchaudio==2.1.1 pytorch-cuda=11.8 -c pytorch -c nvidia
`
`pip install diffusers==0.16.1
`
`pip install transformers==4.32.1 
`
Thank you and congratulations again!

**Comment by HyelinNAM** [comment]
Hi CostaliyA!

Thank you for great suggestion :) I wasn't aware of it.
Let me modify requirements file. Thanks a lot!
