### ISSUE TITLE
Style Transfer in CDS

### ISSUE THREAD

**Issue by ntua-el19019** [HyelinNAM/ContrastiveDenoisingScore#7]
Hi, congratulations on CVPR24! I have a question, I want your insight on whether you believe CDS holds potential for incorporating style guidance to better handle prompts that have styles in them?Where would one focus on to incorporate it?

**Comment by HyelinNAM** [comment]
Hi @ntua-el19019! 

I experimented with style transfer using both DDS and CDS, but found that the score distillation framework might not be well-suited for tasks like style transfer. While simpler style transfers, such as those not requiring consideration of overall image composition like 'snowy' or 'sunset', worked reasonably well, more complex prompts like 'gogh style' did not yield satisfactory results. I think this would be one great future research topic :) 

I hope my experience help you and thank you for your interest :)

Best,
Hyelin

**Comment by ntua-el19019** [comment]
Thank you for your excellent response!That is what I observed too, artist styles are not well represented. I experiment with ways to refine the total loss function to incorporate a style component for guidance and hence I wanted a little insight. Congratulations again and stay curious!
