### ISSUE TITLE
Inquiry to implement gradient change in Fig.5

### ISSUE THREAD

**Issue by john09282922** [HyelinNAM/ContrastiveDenoisingScore#8]
Hi, 
I would like to follow your gradient changes. How can I see the picture?

thanks,
Jungmin

**Comment by HyelinNAM** [comment]
Hi Jungmin!

For gradient maps, I'm cannot remember exactly... but I think I just decode delta denoising score (epsilon difference) using below code and resize it.
https://discuss.huggingface.co/t/decoding-latents-to-rgb-without-upscaling/23204/5

Hope these help you! 

Best, 
Hyelin
